services:
  db:
    image: postgres:16
    container_name: timeline_db
    environment:
      POSTGRES_DB: timelines
      POSTGRES_USER: timelines_user
      POSTGRES_PASSWORD: timelines_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
